### ISSUE TITLE
Feature/PartyDonations

### ISSUE THREAD

**Issue by RichardKruemmel** [FaceTheFacts/backend#132]
- [x] Scrape Data from `https://www.bundestag.de/parlament/praesidium/parteienfinanzierung/fundstellen50000`
- [x] Scrape pdfs for the years 2002 - 2008 from https://www.bundestag.de/parlament/praesidium/parteienfinanzierung/fundstellen50000 @romeonicholas 

![Screenshot 2022-01-05 at 17 27 49](https://user-images.githubusercontent.com/61158193/148253502-eac1c4a2-6c7f-4ff9-ad3e-9fb291deff57.png)

- [x] Create new Table

![Screenshot 2022-01-05 at 17 24 42](https://user-images.githubusercontent.com/61158193/148252722-f1f97db5-53ac-4366-91d2-c833fe0440a1.png)

- [x] Populate Table with Scaped Data 
- [x] Create Route returning PartyDonations ordered by Date @romeonicholas

**Comment by romeonicholas** [comment]
I just sent the file 2002-2008_Donations.json in our slack. Right now it's set up with:

-  Party: string, initials of the party (e.g. FDP, CDU)
- Amount: string, comma for indicating cents (e.g. 19850,44)
- Donor: string, _most_ of them are "Name (newline) Street and number (newline) zip code and city", but there are weird exceptions for foreign ones or ones with additional information I didn't recognize
- Date: string, DD.MM.YYYY

These are the oldest donations and they just don't follow very consistent formatting throughout the years, I'm hoping scraping the newer ones will be more straightforward but I haven't spent much time reviewing the last few years. I'll probably have to do a manual review once they're in the database to clean up anything I missed

**Comment by romeonicholas** [comment]
Tasks complete! I merged Matti's DB work into my branch, and the latest ([available here](https://github.com/FaceTheFacts/backend/compare/feature/132/party-donations-route?expand=1)) should be ready for review @RichardKruemmel. Currently only tested on the FastAPI docs page (v1/partydonations), but will look into getting at least a basic automated test added. Example response:
<img width="319" alt="Screenshot 2022-09-23 at 17 09 08" src="https://user-images.githubusercontent.com/79602065/191993067-5e663be7-ff16-4161-a977-fcc32543b317.png">
