### ISSUE TITLE
Alter occupations

### ISSUE THREAD

**Issue by Fingolf6455** [FaceTheFacts/backend#2]
We need to alter some occupations, because abgeordnetenwatch has them wrong, so it would be good to save them so we are able to alter them. For example Olaf Scholz should be the Minster of Finance.

## Options
- database
- py-file in `data` module
- ...

**Comment by Urhengulas** [comment]
That is definitely possible.

Additionally we could maybe discuss with AW that we send them mistakes we find in order to improve the base dataset. Both we and AW would benefit from that.

**Comment by Fingolf6455** [comment]
Test List:

**Robert Habeck:**

Parteivorsitzender, Schriftstelller

**Olaf Scholz**

Finanzminister, Kanzlerkandidat

**Karl Lauterbach**

MdB

**Christian Lindner**

MdB, Fraktionsvorsitzender, Parteivorsitzender

**Armin Laschet**

MdL, Ministerpräsident NRW, Parteivorsitzender, Kanzlerkandidat



Is this list enough?

**Comment by Urhengulas** [comment]
> Test List:
> 
>     * **Robert Habeck**: Parteivorsitzender, Schriftstelller
> 
>     * **Olaf Scholz**: Finanzminister, Kanzlerkandidat
> 
>     * **Karl Lauterbach**: MdB
> 
>     * **Christian Lindner**: MdB, Fraktionsvorsitzender, Parteivorsitzender
> 
>     * **Armin Laschet**: MdL, Ministerpräsident NRW, Parteivorsitzender, Kanzlerkandidat
> 
> 
> Is this list enough?

That's perfect. Thank you!
