### ISSUE TITLE
Save Pictures of candidates

### ISSUE THREAD

**Issue by Fingolf6455** [FaceTheFacts/backend#6]
The pictures of the candidates aren't available in the AW-api, but we want to provide them to our users.

# Open questions
* Where to store the images?
* Where to store the links to the images, in order to give them to the frontend?
  * In theory there is also the option to directly send the image with the HTTP-response, but I somehow feel like this isn't a god idea, although I am not sure why.

## Options
* Where to store the images?
  * images into object store, with link containing the `politician_id`. something like `https://s3.aws.com/politician_image-<politician_id>.png`
  * don't store them at all, but use the ones on the abgeordnetenwatch website
  * images into database, using a byte-datatype
* Where to store the links to the images?
  * py-file
  * RDMS (postgres)
  * key-value store (redis, cassandra)

**Comment by Urhengulas** [comment]
I am currently thinking to use an object store (like AWS S3) for the images, store the references in a database and hand out the direct references to the object store to the frontend.

**Comment by Urhengulas** [comment]
@Fingolf6455 Are we allowed to store the images? Or are we only allowed to store the links to the images? (copyright)

**Comment by Urhengulas** [comment]
Status update
- [x] @m-lukas collect images https://github.com/FaceTheFacts/image-scraper
- [x] @m-lukas store images (e.g. https://candidate-images.s3.eu-central-1.amazonaws.com/79475.jpg)
- [ ] integrate images intro frontend

**Comment by Urhengulas** [comment]
Fixed by #33
