### ISSUE TITLE
Save Politician Name and party

### ISSUE THREAD

**Issue by Fingolf6455** [FaceTheFacts/backend#8]
It would be very beneficial if we can somehow save the name of the politician and his party to get a database the Scanfeature can be trained with.

**Comment by Urhengulas** [comment]
I am not sure if I understand why this would be useful. Can you please elaborate (in person)?

**Comment by Urhengulas** [comment]
And even if it is needed to train the model with this data (which I am unsure about), we probably want to store it in a csv-file.
