### ISSUE TITLE
Merge the data we save to one API call

### ISSUE THREAD

**Issue by Fingolf6455** [FaceTheFacts/backend#9]
It would be amazing if we can save all the data  we have about a candidate in one API call so we are faster and also the data is more structured towards our needs.

**Comment by Urhengulas** [comment]
I am honestly not sure if having one huge API-call is necessarily faster than a few smaller ones. I think (assumption!) smartphones and web-browser are able to fetch multiple things in parallel. If then one call is already finished the client can go on processing and rendering with that data. While if you would have one big call, this might not be possible.
